pretraining:
  data_dir: "/path/to/tfrecords/"
  batch_size: 1
  epochs: 1000
  experiment_name: "name_of_model"
  loss_type: "huber"
  learning_rate: 0.0001
  out_dir: "/path/to/save/models/"
  inputs: [thk, usurf] # note these can be different from iceflow.unified.inputs - you can train a network for only a subset of the inputs used in iceflow simulations
  resume: false